name: "CodeQL U-Boot Scan"

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:     

jobs:
  analyze:
    name: Analyze C/C++
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: cpp
        # Il percorso punta correttamente alla cartella mostrata nel primo screenshot
        queries: ./4.StaticAnalysis/query_github_actions/10_taint_tracking.ql

    - name: Install U-Boot Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bison flex device-tree-compiler libsdl2-dev

    - name: Build U-Boot (Tracciato da CodeQL)
      run: |
        cd 4.StaticAnalysis/u-boot/
        
        # Configura U-Boot per l'architettura sandbox
        make sandbox_defconfig
        
        # Compila il codice aggiungendo la parentesi di chiusura a $(nproc)
        make KCFLAGS="-fcommon" -j$(nproc)

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:cpp"
